version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "104"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  graphql:
    image: zenith110/portfolio-graphql
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    container_name: graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "8443:8443"
    # env_file:
    #   - .env
  emailcow:
    image: mailcow/sogo
  teleport:
    image: quay.io/gravitational/teleport:8
    container_name: teleport
    entrypoint: /bin/sh
    hostname: luna.teleport
    command: -c "config"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:443"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
      - ./certs:/mnt/shared/certs
