version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "104"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # frontend:
  #   image: zenith110/frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: dev.dockerfile
  #   container_name: frontend
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
  #   restart: unless-stopped
  #   ports:
  #     - "5000:5000"
  graphql:
    image: zenith110/portfolio-graphql
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    container_name: graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
  configure:
    image: quay.io/gravitational/teleport:8
    container_name: teleport-configure
    entrypoint: /bin/sh
    hostname: teleport.abrahannevarez.dev
    command: -c "if [ ! -f /etc/teleport/teleport.yaml ]; then teleport configure > /etc/teleport/teleport.yaml; fi"
    volumes:
      - ./teleport-config:/etc/teleport

  teleport:
    image: quay.io/gravitational/teleport:8
    container_name: teleport
    entrypoint: /bin/sh
    hostname: teleport.abrahannevarez.dev
    command: -c "sleep 1 && /bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./teleport-config:/etc/teleport
      - ./teleport-data:/var/lib/teleport
    depends_on:
      - configure
