version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 4000:4000
    user: "104"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  graphql:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    container_name: graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    labels:
      - "traefik.http.routers.home.rule=Host(`graphqlapi.localhost`)"
      - "traefik.http.services.home.loadbalancer.server.port=8443"
    ports:
      - 8443:8443
    env_file:
      - .env
  portfolio:
    build:
      context: ./frontend/frontpage
      dockerfile: dev.dockerfile
    container_name: portfolio
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend/frontpage:/home/app/portfolio
    env_file:
      - .env
    depends_on:
      - graphql
  admin:
    build:
      context: ./frontend/admin-panel
      dockerfile: dev.dockerfile
    container_name: admin
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend/admin-panel:/home/app/admin-tool
    env_file:
      - .env
    depends_on:
      - graphql
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  configure:
    image: quay.io/gravitational/teleport:8
    container_name: teleport-configure
    entrypoint: /bin/sh
    hostname: teleport.abrahannevarez.dev
    command: -c "if [ ! -f /etc/teleport/teleport.yaml ]; then teleport configure > /etc/teleport/teleport.yaml; fi"
    volumes:
      - ./teleport-config:/etc/teleport

  teleport:
    image: quay.io/gravitational/teleport:8
    container_name: teleport
    entrypoint: /bin/sh
    hostname: teleport.abrahannevarez.dev
    command: -c "sleep 1 && /bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./teleport-config:/etc/teleport
      - ./teleport-data:/var/lib/teleport
    depends_on:
      - configure
