version: "3"

services:
  graphql:
    build:
      context: ./Portfolio-Backend
      dockerfile: dev.dockerfile
    container_name: graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - 8443:8443
    env_file:
      - .env
  portfolio:
    build:
      context: ./frontend/frontpage
      dockerfile: dev.dockerfile
    container_name: portfolio
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules
      - ./frontend/frontpage:/home/app/portfolio
    depends_on:
      - graphql
    env_file:
      - .env

