version: "3"

services:
  graphql:
    build:
      context: ./Portfolio-Backend
      dockerfile: dev.dockerfile
    container_name: portfolio-graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
  portfolio:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    container_name: portfolio-frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - "80:5173"
    depends_on:
      - graphql
    env_file:
      - .env


