// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccessCode struct {
	StatusCode    string `json:"statusCode"`
	AllowedAccess bool   `json:"allowedAccess"`
}

type Article struct {
	Name        string     `json:"name"`
	Author      *Author    `json:"author"`
	ContentData []*Content `json:"contentData"`
	DateWritten string     `json:"dateWritten"`
	URL         string     `json:"url"`
}

type Articles struct {
	Articles []*Article `json:"articles"`
	Total    int        `json:"total"`
}

type Author struct {
	Name    string `json:"name"`
	Profile string `json:"profile"`
	Picture string `json:"picture"`
}

type Content struct {
	Images  []*Image `json:"images"`
	Content string   `json:"content"`
}

type GithubProjects struct {
	Projects []*Project `json:"projects"`
}

type Image struct {
	URL string `json:"url"`
}

type LoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewArticle struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type Project struct {
	Name   string `json:"name"`
	Tags   []*Tag `json:"tags"`
	Link   string `json:"link"`
	Readme string `json:"readme"`
}

type Tag struct {
	Language string `json:"language"`
	Image    string `json:"image"`
}
