// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	Name        string     `json:"name"`
	Author      string     `json:"author"`
	Content     []*Content `json:"content"`
	DateWritten string     `json:"dateWritten"`
	URL         string     `json:"url"`
}

type Articles struct {
	Articles []*Article `json:"articles"`
}

type BoldText struct {
	Text string `json:"text"`
}

type Content struct {
	Images        []*Image        `json:"images"`
	BoldTexts     []*BoldText     `json:"boldTexts"`
	ItalizedTexts []*ItalizedText `json:"italizedTexts"`
}

type Image struct {
	URL string `json:"url"`
}

type ItalizedText struct {
	Text string `json:"text"`
}

type NewArticle struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}
