// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AccessCode struct {
	StatusCode    string `json:"statusCode"`
	AllowedAccess bool   `json:"allowedAccess"`
}

type Article struct {
	Title       string  `json:"title"`
	TitleCard   string  `json:"titleCard"`
	Author      *Author `json:"author"`
	ContentData string  `json:"contentData"`
	DateWritten string  `json:"dateWritten"`
	URL         string  `json:"url"`
	Description string  `json:"description"`
	UUID        string  `json:"uuid"`
	Tags        []Tag   `json:"tags"`
}

type ArticleTag struct {
	Keyword string `json:"keyword"`
}

type ArticleTagInput struct {
	Keyword string `json:"keyword"`
}

type Articles struct {
	Article []Article `json:"article"`
	Total   int       `json:"total"`
}

type Author struct {
	Name    string `json:"name"`
	Profile string `json:"profile"`
	Picture string `json:"picture"`
}

type AuthorInput struct {
	Name    string `json:"name"`
	Profile string `json:"profile"`
	Picture string `json:"picture"`
}

type CreateArticleInfo struct {
	Title       *string   `json:"title"`
	TitleCard   *File     `json:"titleCard"`
	Author      *string   `json:"author"`
	ContentData *string   `json:"contentData"`
	DateWritten *string   `json:"dateWritten"`
	URL         *string   `json:"url"`
	Description *string   `json:"description"`
	UUID        *string   `json:"uuid"`
	Tags        []TagData `json:"tags"`
}

type File struct {
	Name        *string         `json:"name"`
	FileData    *graphql.Upload `json:"fileData"`
	ContentType *string         `json:"contentType"`
}

type Gallery struct {
	Images []Image `json:"images"`
}

type GithubProjects struct {
	Projects []*Project `json:"projects"`
}

type Image struct {
	URL string `json:"url"`
}

type LoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Project struct {
	Name           string   `json:"name"`
	Githublink     string   `json:"githublink"`
	Description    string   `json:"description"`
	Createdon      string   `json:"createdon"`
	Languages      []Tag    `json:"languages"`
	Topics         []string `json:"topics"`
	Deploymentlink string   `json:"deploymentlink"`
}

type Tag struct {
	Language string `json:"language"`
}

type TagData struct {
	Name *string `json:"name"`
}

type UpdatedArticleInfo struct {
	Title       *string   `json:"title"`
	TitleCard   *File     `json:"titleCard"`
	Author      *string   `json:"author"`
	ContentData *string   `json:"contentData"`
	DateWritten *string   `json:"dateWritten"`
	URL         *string   `json:"url"`
	Description *string   `json:"description"`
	UUID        *string   `json:"uuid"`
	Tags        []TagData `json:"tags"`
}
